"""Generate the classic recipe catalog from the closed metadata table."""

from __future__ import annotations

import argparse
from pathlib import Path

from reprobit.costs import CostModel
from reprobit.intervention_metadata import (
    CLASSIC_RECIPE_METADATA,
    ClassicRecipeFamily,
    FamilyExecutionMode,
    classic_recipe_family_label,
)


def render_recipe_reference() -> str:
    """Render stable descriptive metadata without importing recipe dispatchers."""

    lines = [
        "# Classic recipe reference",
        "",
        "Generated by `python -m reprobit.recipe_reference`; do not edit this table by hand.",
        "Roles, labels, cost classes, and execution coverage come from",
        "`reprobit.intervention_metadata`; per-unit weights come from `reprobit.costs.CostModel`.",
        "",
        "Availability describes the library's implementation. A recipe still needs valid",
        "parameters, its semantic proof, and fresh verification before it can certify a result.",
        "See [Interventions](interventions.md) for each family's behavior and proof requirements",
        "and [Costs](costs.md) for cost attribution.",
        "",
        "| Family | Role | Human label | Cost class (points per unit) | "
        "Execution path | Availability |",
        "|---|---|---|---|---|---|",
    ]
    for family in ClassicRecipeFamily:
        metadata = CLASSIC_RECIPE_METADATA[family]
        role = f"`{metadata.role.value}`" if metadata.role is not None else "—"
        cost = (
            f"`{metadata.cost_class.value}` ({CostModel.weights[metadata.cost_class]:,})"
            if metadata.cost_class is not None
            else "Not costable as a classic recipe"
        )
        availability = "Available" if metadata.coverage.implemented else "Unavailable"
        if metadata.coverage.mode is FamilyExecutionMode.QUARANTINE_ONLY:
            availability = "Use `legacy.oracle_install`"
        label = classic_recipe_family_label(family) if metadata.role is not None else "—"
        lines.append(
            f"| `{family.value}` | {role} | {label} | {cost} | "
            f"`{metadata.coverage.mode.value}` | {availability} |"
        )
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check", action="store_true", help="Fail if the committed catalog is stale"
    )
    parser.add_argument("--output", type=Path, default=Path("docs/classic-recipe-reference.md"))
    args = parser.parse_args()
    rendered = render_recipe_reference()
    if args.check:
        if not args.output.is_file() or args.output.read_text(encoding="utf-8") != rendered:
            parser.exit(1, f"{args.output} is stale; run python -m reprobit.recipe_reference\n")
        return 0
    args.output.write_text(rendered, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())


__all__ = ["render_recipe_reference"]
